[[redirects]]
  from = "/v2/*"
  to = "https://confident-engelbart-deba5c.netlify.app/:splat"
  status = 200
  force = true
  
# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
